# Generated by Django 2.2.4 on 2019-08-04 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('student_number', models.IntegerField(primary_key=True, serialize=False)),
                ('given_name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=5)),
                ('year', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta.TeachingAssistant')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta.Course')),
            ],
        ),
    ]
