# Generated by Django 2.2.4 on 2019-08-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['rank']},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'course')},
        ),
    ]
