# Generated by Django 2.2.4 on 2019-08-30 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0003_auto_20190830_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta.Course'),
        ),
    ]
